# -*- coding: utf-8 -*-
"""GloVe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyO808pJYjjPqbF60geRnbsa-a3EoFVT
"""

!pip install gensim
!pip install gensim-downloader

import gensim.downloader as api

print("Loading GloVe model...")

glove_model = api.load("glove-wiki-gigaword-50")

print("Model Loaded Successfully!")

print("Vocabulary Size:", len(glove_model))

word = "language"

print(f"Word Vector for '{word}':\n")

print(glove_model[word])

print("Most Similar Words:\n")

similar_words = glove_model.most_similar("language", topn=10)

for word, score in similar_words:
    print(f"{word:<15} {score:.4f}")

similarity = glove_model.similarity("language", "processing")

print("Similarity Score:", similarity)

result = glove_model.most_similar(
    positive=["king", "woman"],
    negative=["man"],
    topn=5
)

print(result)

word = input("Enter a word: ").lower()

if word in glove_model:
    print("\nTop 10 Similar Words:\n")

    for w, score in glove_model.most_similar(word):
        print(f"{w:<15} {score:.4f}")
else:
    print("Word not found in vocabulary.")

word1 = input("Enter first word: ").lower()
word2 = input("Enter second word: ").lower()

if word1 in glove_model and word2 in glove_model:
    print("Similarity:", glove_model.similarity(word1, word2))
else:
    print("One or both words are not present in the vocabulary.")